In [1]:

import numpy as np

import pandas as pd

In [2]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [3]:
movies.shape

(4803, 20)

In [4]:
credits.shape

(4803, 4)

In [5]:
movies = movies.merge(credits,on='title')
movies.shape

(4809, 23)

In [6]:
movies

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4804,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]",...,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238,9367,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],...,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5,72766,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...",...,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6,231617,"[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],...,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7,126186,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...",...,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16,25975,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [7]:
'''
genres
id
keywords 
overview
title 
cast 
crew
'''

movies = movies[['id','genres','keywords','overview','title','cast','crew']]
movies.head()

,id,genres,keywords,overview,title,cast,crew
0,19995,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...",Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bondâ€™s past sends him o...,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...",John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [8]:
movies.isnull().sum()

id          0
genres      0
keywords    0
overview    3
title       0
cast        0
crew        0
dtype: int64

In [9]:
movies.dropna(inplace=True)

C:\Users\Shree\anaconda3\lib\site-packages\pandas\util\_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

In [10]:
movies.isnull().sum()

id          0
genres      0
keywords    0
overview    0
title       0
cast        0
crew        0
dtype: int64

In [11]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [12]:
import ast

def convert(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [13]:
movies['genres'] = movies['genres'].apply(convert)
movies['keywords'] = movies['keywords'].apply(convert)

C:\Users\Shree\AppData\Local\Temp/ipykernel_5688/2230006191.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['genres'] = movies['genres'].apply(convert)
C:\Users\Shree\AppData\Local\Temp/ipykernel_5688/2230006191.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['keywords'] = movies['keywords'].apply(convert)

In [14]:

# taking only first three casts

def convert3(obj):
    L = []
    counter=0
    for i in ast.literal_eval(obj):
        if counter != 3:
            L.append(i['name'])
            counter+=1
        else:
            break
    return L

In [15]:
movies['cast'] = movies['cast'].apply(convert3)

C:\Users\Shree\AppData\Local\Temp/ipykernel_5688/3593664571.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['cast'] = movies['cast'].apply(convert3)

In [16]:

def convertDirector(obj):
    L = []
    for i in ast.literal_eval(obj):
        if i['job']=='Director':
            L.append(i['name'])
            break
    return L

In [17]:
movies['crew'] = movies['crew'].apply(convertDirector)

C:\Users\Shree\AppData\Local\Temp/ipykernel_5688/3104842067.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['crew'] = movies['crew'].apply(convertDirector)

In [18]:
movies.head()

,id,genres,keywords,overview,title,cast,crew
0,19995,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...",Avatar,"[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,"[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bondâ€™s past sends him o...,Spectre,"[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes]
3,49026,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,The Dark Knight Rises,"[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...",John Carter,"[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [19]:
# now all data is preprocessed 
#create a new column named 'tag' in which all genres , keywords , overview , cast and crew

'''

overview is string convert it into list 

'''

movies['overview'] = movies['overview'].apply(lambda x:x.split())

C:\Users\Shree\AppData\Local\Temp/ipykernel_5688/3542370253.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [20]:
movies.head()

,id,genres,keywords,overview,title,cast,crew
0,19995,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[In, the, 22nd, century,, a, paraplegic, Marin...",Avatar,"[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Captain, Barbossa,, long, believed, to, be, d...",Pirates of the Caribbean: At World's End,"[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[A, cryptic, message, from, Bondâ€™s, past, send...",Spectre,"[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes]
3,49026,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Following, the, death, of, District, Attorney...",The Dark Knight Rises,"[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[John, Carter, is, a, war-weary,, former, mili...",John Carter,"[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [21]:
movies['tag'] = movies['genres'] + movies['keywords'] + movies['overview'] + movies['cast'] + movies['crew']

C:\Users\Shree\AppData\Local\Temp/ipykernel_5688/1431659032.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tag'] = movies['genres'] + movies['keywords'] + movies['overview'] + movies['cast'] + movies['crew']

In [22]:
movies.head()

,id,genres,keywords,overview,title,cast,crew,tag
0,19995,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[In, the, 22nd, century,, a, paraplegic, Marin...",Avatar,"[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron],"[Action, Adventure, Fantasy, Science Fiction, ..."
1,285,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Captain, Barbossa,, long, believed, to, be, d...",Pirates of the Caribbean: At World's End,"[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski],"[Adventure, Fantasy, Action, ocean, drug abuse..."
2,206647,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[A, cryptic, message, from, Bondâ€™s, past, send...",Spectre,"[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes],"[Action, Adventure, Crime, spy, based on novel..."
3,49026,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Following, the, death, of, District, Attorney...",The Dark Knight Rises,"[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan],"[Action, Crime, Drama, Thriller, dc comics, cr..."
4,49529,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[John, Carter, is, a, war-weary,, former, mili...",John Carter,"[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton],"[Action, Adventure, Science Fiction, based on ..."

In [23]:
'''

Remove all the space between words because
Sam Worthington   --> SamWorthington

to differentiate betwn 
[Sam Mendes] and [Sam Worthington]

'''

'\n\nRemove all the space between words because\nSam Worthington   --> SamWorthington\n\nto differentiate betwn \n[Sam Mendes] and [Sam Worthington]\n\n'

In [24]:
movies['genres'] = movies['genres'].apply(lambda x : [i.replace(" ","") for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x : [i.replace(" ","") for i in x])
movies['cast'] = movies['cast'].apply(lambda x : [i.replace(" ","") for i in x])
movies['crew'] = movies['crew'].apply(lambda x : [i.replace(" ","") for i in x])

C:\Users\Shree\AppData\Local\Temp/ipykernel_5688/170439679.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['genres'] = movies['genres'].apply(lambda x : [i.replace(" ","") for i in x])
C:\Users\Shree\AppData\Local\Temp/ipykernel_5688/170439679.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['keywords'] = movies['keywords'].apply(lambda x : [i.replace(" ","") for i in x])
C:\Users\Shree\AppData\Local\Temp/ipykernel_5688/170439679.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['cast'] = movies['cast'].apply(lambda x : [i.replace(" ","") for i in x])
C:\Users\Shree\AppData\Local\Temp/ipykernel_5688/170439679.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['crew'] = movies['crew'].apply(lambda x : [i.replace(" ","") for i in x])

In [25]:
movies.head()

,id,genres,keywords,overview,title,cast,crew,tag
0,19995,"[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[In, the, 22nd, century,, a, paraplegic, Marin...",Avatar,"[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[Action, Adventure, Fantasy, Science Fiction, ..."
1,285,"[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[Captain, Barbossa,, long, believed, to, be, d...",Pirates of the Caribbean: At World's End,"[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Adventure, Fantasy, Action, ocean, drug abuse..."
2,206647,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[A, cryptic, message, from, Bondâ€™s, past, send...",Spectre,"[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes],"[Action, Adventure, Crime, spy, based on novel..."
3,49026,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[Following, the, death, of, District, Attorney...",The Dark Knight Rises,"[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Action, Crime, Drama, Thriller, dc comics, cr..."
4,49529,"[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[John, Carter, is, a, war-weary,, former, mili...",John Carter,"[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[Action, Adventure, Science Fiction, based on ..."

In [26]:
movies = movies[['id','title','tag']]

In [27]:
movies.head()

,id,title,tag
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction, ..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action, ocean, drug abuse..."
2,206647,Spectre,"[Action, Adventure, Crime, spy, based on novel..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller, dc comics, cr..."
4,49529,John Carter,"[Action, Adventure, Science Fiction, based on ..."

In [28]:
#converting list into string 
movies['tag'] = movies['tag'].apply(lambda x:" ".join(x))
movies['tag']

0       Action Adventure Fantasy Science Fiction cultu...
1       Adventure Fantasy Action ocean drug abuse exot...
2       Action Adventure Crime spy based on novel secr...
3       Action Crime Drama Thriller dc comics crime fi...
4       Action Adventure Science Fiction based on nove...
                              ...
4804    Action Crime Thriller united statesâ€“mexico bar...
4805    Comedy Romance A newlywed couple's honeymoon i...
4806    Comedy Drama Romance TV Movie date love at fir...
4807    When ambitious New York attorney Sam is sent t...
4808    Documentary obsession camcorder crush dream gi...
Name: tag, Length: 4806, dtype: object

In [29]:
movies.head()

,id,title,tag
0,19995,Avatar,Action Adventure Fantasy Science Fiction cultu...
1,285,Pirates of the Caribbean: At World's End,Adventure Fantasy Action ocean drug abuse exot...
2,206647,Spectre,Action Adventure Crime spy based on novel secr...
3,49026,The Dark Knight Rises,Action Crime Drama Thriller dc comics crime fi...
4,49529,John Carter,Action Adventure Science Fiction based on nove...

In [30]:
#converting all into lower case
movies['tag'] = movies['tag'].apply(lambda x:x.lower())

In [31]:
movies.head()

,id,title,tag
0,19995,Avatar,action adventure fantasy science fiction cultu...
1,285,Pirates of the Caribbean: At World's End,adventure fantasy action ocean drug abuse exot...
2,206647,Spectre,action adventure crime spy based on novel secr...
3,49026,The Dark Knight Rises,action crime drama thriller dc comics crime fi...
4,49529,John Carter,action adventure science fiction based on nove...

In [32]:

'''
many of words like love , loved , loving are of same meaning so we have to replace all these types of words by base word

this is done by steamming nlti library

'''

from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
        
    return " ".join(y)  #convert it into string again

In [33]:
movies['tag'] = movies['tag'].apply(stem)

# converting text into vectors

In [34]:
'''
By using method bag of words
other techniques
    1. word to vect
    2. if idf
    
    
How it work
 
 combine all the tags and then find frequency of each word in that combined tag take 5000 most frequent words
 now take each tag and find frequency of tag -> this is the vector of that movie
 
     action | science | fun | History ...(top 5000 words) -> most frequent words from combined tag 
 m1     4        2       1      0     ...  -> this is the vector of m1 movie
 m2     1        1       3      2     ...  -> this is the vector of m2 movie
 m3     0        1       1      4     ...  -> this is the vector of m3 movie
 .
 .
 .
 (5000 movies)
 (5000,5000) shape of vector
 
 
 IMPORTANT
 
 here we ignore the stop words 
 stop words -> used to frame the sentances but not related to meaning
 e.g. are,a,the,to,from
 
'''

'\nBy using method bag of words\nother techniques\n    1. word to vect\n    2. if idf\n    \n    \nHow it work\n \n combine all the tags and then find frequency of each word in that combined tag take 5000 most frequent words\n now take each tag and find frequency of tag -> this is the vector of that movie\n \n     action | science | fun | History ...(top 5000 words) -> most frequent words from combined tag \n m1     4        2       1      0     ...  -> this is the vector of m1 movie\n m2     1        1       3      2     ...  -> this is the vector of m2 movie\n m3     0        1       1      4     ...  -> this is the vector of m3 movie\n .\n .\n .\n (5000 movies)\n (5000,5000) shape of vector\n \n \n IMPORTANT\n \n here we ignore the stop words \n stop words -> used to frame the sentances but not related to meaning\n e.g. are,a,the,to,from\n \n'

In [35]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000 , stop_words='english')  #max_features max number of words , stop_words

In [36]:
vectors = cv.fit_transform(movies['tag']).toarray()     #converting transform to array
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [37]:
vectors.shape

(4806, 5000)

In [38]:
# see the 5000 most frequent names
cv.get_feature_names()

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '16th',
 '17',
 '17th',
 '18',
 '18th',
 '19',
 '1910',
 '1920',
 '1930',
 '1940',
 '1950',
 '1950s',
 '1960',
 '1960s',
 '1970',
 '1970s',
 '1980',
 '1985',
 '1990',
 '19th',
 '20',
 '200',
 '2009',
 '20th',
 '21st',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '51',
 '60',
 '70',
 'aaron',
 'abandon',
 'abbi',
 'abduct',
 'abel',
 'abigail',
 'abil',
 'abl',
 'aboard',
 'aborigin',
 'abov',
 'abraham',
 'abroad',
 'abus',
 'academi',
 'accent',
 'accept',
 'access',
 'accid',
 'accident',
 'acclaim',
 'accompani',
 'accomplish',
 'account',
 'accus',
 'ace',
 'achiev',
 'act',
 'action',
 'activ',
 'activist',
 'activities',
 'actor',
 'actress',
 'actual',
 'ad',
 'adam',
 'adapt',
 'add',
 'addict',
 'adjust',
 'admir',
 'admit',
 'adolesc',
 'adolf',
 'adopt',
 'ador',
 'adrian',
 'adrien',
 'adult',
 'adulteri',
 'adulthood',
 'advanc',
 'adventur',
 'adventure',
 'advertis',
 'advic',
 'advis',
 'affair',
 'affect',
 'affleck',
 'afghanistan',
 'africa',
 'african',
 'aftercreditssting',
 'afterlif',
 'aftermath',
 'ag',
 'age',
 'agenc',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggress',
 'ago',
 'agre',
 'ahead',
 'aid',
 'aidan',
 'ail',
 'aim',
 'air',
 'aircraft',
 'airplan',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alaska',
 'alba',
 'albert',
 'alcohol',
 'alec',
 'alejandro',
 'alex',
 'alexand',
 'alexi',
 'alfr',
 'ali',
 'alic',
 'alice',
 'alicia',
 'alien',
 'alik',
 'alison',
 'aliv',
 'alive',
 'allan',
 'allen',
 'alli',
 'allianc',
 'allison',
 'allow',
 'alon',
 'alongsid',
 'alpha',
 'alreadi',
 'alter',
 'altern',
 'alway',
 'alyssa',
 'alzheimer',
 'amanda',
 'amateur',
 'amaz',
 'amazon',
 'ambassador',
 'amber',
 'ambigu',
 'ambit',
 'ambiti',
 'ambul',
 'ambush',
 'america',
 'american',
 'ami',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amsterdam',
 'amus',
 'amy',
 'ana',
 'analyst',
 'anarch',
 'ancient',
 'anderson',
 'andi',
 'andrea',
 'andrew',
 'android',
 'andrÃ©',
 'andy',
 'ang',
 'angarano',
 'angel',
 'angela',
 'angeles',
 'angelina',
 'anger',
 'angri',
 'angst',
 'ani',
 'anim',
 'animals',
 'aniston',
 'ann',
 'anna',
 'annabel',
 'annett',
 'anni',
 'annie',
 'anniversari',
 'announc',
 'annual',
 'anonym',
 'anoth',
 'answer',
 'ant',
 'antholog',
 'anthoni',
 'anthropomorph',
 'anti',
 'antoin',
 'anton',
 'antonio',
 'anyon',
 'anyth',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apocalyps',
 'apocalypt',
 'appar',
 'appear',
 'appl',
 'appleg',
 'appoint',
 'appreci',
 'apprentic',
 'approach',
 'april',
 'arab',
 'arch',
 'archaeologist',
 'archeolog',
 'archer',
 'architect',
 'arctic',
 'area',
 'aren',
 'arena',
 'argument',
 'aris',
 'aristocrat',
 'arkin',
 'arm',
 'armand',
 'armi',
 'armor',
 'armstrong',
 'army',
 'arnold',
 'aronofski',
 'arquett',
 'arrang',
 'arrest',
 'arriv',
 'arrog',
 'arrow',
 'art',
 'arthur',
 'articl',
 'artifact',
 'artifici',
 'artist',
 'ash',
 'ashley',
 'ashton',
 'asia',
 'asian',
 'asid',
 'ask',
 'aspect',
 'aspir',
 'assassin',
 'assault',
 'assign',
 'assist',
 'assistant',
 'associ',
 'assum',
 'asteroid',
 'astin',
 'astronaut',
 'asylum',
 'athlet',
 'atkin',
 'atlant',
 'atom',
 'attack',
 'attacks',
 'attempt',
 'attend',
 'attent',
 'attitud',
 'attorney',
 'attract',
 'auction',
 'audienc',
 'audit',
 'audrey',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'austria',
 'author',
 'autism',
 'auto',
 'autobiograph',
 'automobil',
 'aveng',
 'averag',
 'avoid',
 'await',
 'awaken',
 'award',
 'away',
 'awkward',
 'awri',
 'awry',
 'ax',
 'axe',
 'aykroyd',
 'babe',
 'babi',
 'baby',
 'bachchan',
 'bachelor',
 'backdrop',
 'background',
 'backpack',
 'bacon',
 'bad',
 'bag',
 'bahama',
 'bail',
 'bailey',
 'baker',
 'balanc',
 'baldwin',
 'bale',
 'ball',
 'ballet',
 'balloon',
 'baltimor',
 'ban',
 'bana',
 'band',
 'bandera',
 'bandit',
 'bangkok',
 'banish',
 'bank',
 'banker',
 'banner',
 'bar',
 'barbara',
 'barbarian',
 'bardem',
 'bare',
 'bargain',
 'barn',
 'barney',
 'baron',
 'barri',
 'barrier',
 'barrymor',
 'bart',
 'bas',
 'base',
 'basebal',
 'basement',
 'basing',
 'basketbal',
 'basketball',
 'bassett',
 'bat',
 'bate',
 'bateman',
 'bath',
 'bathroom',
 'batman',
 'battl',
 'battle',
 'battlefield',
 'bay',
 'beach',
 'beam',
 'bean',
 'bear',
 'beard',
 'beast',
 'beat',
 'beatti',
 'beauti',
 'beautiful',
 'beauty',
 'becam',
 'becaus',
 'beck',
 'becker',
 'becki',
 'beckinsal',
 'becom',
 'bed',
 'bedroom',
 'bee',
 'beer',
 'befor',
 'befriend',
 'began',
 'begin',
 'begins',
 'behavior',
 'belgium',
 'belief',
 'believ',
 'bell',
 'bella',
 'bello',
 'belong',
 'belov',
 'belt',
 'ben',
 'bend',
 'bene',
 'beneath',
 'benefit',
 'benicio',
 'benjamin',
 'bennett',
 'bent',
 'bentley',
 'berg',
 'bergman',
 'berlin',
 'bernal',
 'berni',
 'berri',
 'best',
 'bet',
 'beth',
 'betray',
 'bett',
 'bettani',
 'better',
 'betti',
 'beverli',
 'bibl',
 'biblic',
 'bicycl',
 'biel',
 'big',
 'bigg',
 'bigger',
 'biggest',
 'bike',
 'biker',
 'bikini',
 'billi',
 'billion',
 'billionair',
 'biographi',
 'biolog',
 'bird',
 'birth',
 'birthday',
 'bisexu',
 'bishop',
 'bit',
 'bite',
 'bitten',
 'bitter',
 'bizarr',
 'black',
 'blackmail',
 'blacksmith',
 'blade',
 'blair',
 'blake',
 'blame',
 'blanchett',
 'bledel',
 'blend',
 'bless',
 'blind',
 'bliss',
 'block',
 'blond',
 'blood',
 'bloodi',
 'bloodthirsti',
 'bloom',
 'blow',
 'blue',
 'blunt',
 'board',
 'boat',
 'bob',
 'bobbi',
 'bodi',
 'body',
 'bodyguard',
 'bold',
 'bollywood',
 'bomb',
 'bond',
 'bone',
 'bonham',
 'bonni',
 'book',
 'booth',
 'border',
 'bore',
 'boredom',
 'born',
 'boss',
 'boston',
 'bosworth',
 'botch',
 'bottl',
 'bound',
 'boundari',
 'bounti',
 'bower',
 'bowl',
 'bowman',
 'box',
 'boxer',
 'boy',
 'boyd',
 'boyfriend',
 'boyl',
 'boys',
 'brad',
 'bradford',
 'bradley',
 'brain',
 'branagh',
 'brand',
 'brando',
 'brandon',
 'bratt',
 'brave',
 'braveri',
 'brazil',
 'brazilian',
 'break',
 'breakdown',
 'breast',
 'breath',
 'breed',
 'brenda',
 'brendan',
 'brent',
 'breslin',
 'brett',
 'brian',
 'bride',
 'bridesmaid',
 'bridg',
 'bridget',
 'brie',
 'brief',
 'brien',
 'bright',
 'brilliant',
 'bring',
 'brink',
 'britain',
 'british',
 'britt',
 'brittani',
 'broadbent',
 'broadcast',
 'broadway',
 'broderick',
 'brodi',
 'broke',
 'broken',
 'broker',
 'brolin',
 'bronx',
 'brook',
 'brooklyn',
 'broom',
 'brosnan',
 'brothel',
 'brother',
 'brothers',
 'brought',
 'brown',
 'bruce',
 'bruno',
 'brutal',
 'bryan',
 'bryce',
 'bu',
 'buck',
 'bud',
 'buddi',
 'buddy',
 'budget',
 'build',
 'building',
 'built',
 'bullet',
 'bulli',
 'bullock',
 'bumbl',
 'bunni',
 'burglar',
 'buri',
 'burk',
 'burn',
 'burstyn',
 'burt',
 'burton',
 'buscemi',
 'bush',
 'busi',
 'business',
 'businessman',
 'bust',
 'butcher',
 'butler',
 'butt',
 'buy',
 'buzz',
 'byrn',
 'caan',
 'cabin',
 'cabl',
 'caesar',
 'cage',
 'cain',
 'cairo',
 'cal',
 'california',
 'calvin',
 'camcord',
 'came',
 'camera',
 'cameraman',
 'cameron',
 'camp',
 'campaign',
 'campbel',
 'campbell',
 'campu',
 'canada',
 'canadian',
 'cancer',
 'candi',
 'candid',
 'canin',
 'cannib',
 'cannon',
 'capabl',
 'caper',
 'capit',
 'capt',
 'captain',
 'captiv',
 'captur',
 'car',
 'card',
 'care',
 'career',
 'carefre',
 'carel',
 'caretak',
 'carey',
 'cargo',
 'cari',
 'caribbean',
 'carl',
 'carla',
 'carlo',
 'carmen',
 'carol',
 'carolin',
 'carolina',
 'carpent',
 'carradin',
 'carrey',
 'carri',
 'carrie',
 'carrier',
 'carrol',
 'cartel',
 'carter',
 'cartoon',
 'case',
 'casey',
 'cash',
 'casino',
 'cassidi',
 'cast',
 'castl',
 'castle',
 'casual',
 'cat',
 'cataclysm',
 'catastroph',
 'catch',
 'cate',
 'catherin',
 'cathol',
 'catholic',
 'cattl',
 'caught',
 'caus',
 'cavalri',
 'cave',
 'caviezel',
 'cedric',
 'celebr',
 'cell',
 'cemeteri',
 'center',
 'centr',
 'central',
 'centuri',
 'centuries',
 'century',
 'certain',
 'chad',
 'chain',
 'chainsaw',
 'chair',
 'challeng',
 'chamber',
 'champion',
 'championship',
 'chan',
 'chanc',
 'chance',
 'chang',
 'change',
 'changes',
 'channel',
 'chao',
 'chaos',
 'chaotic',
 'chapter',
 'charact',
 'character',
 'characters',
 'charg',
 'charismat',
 'charl',
 'charli',
 'charlie',
 'charliz',
 'charlott',
 'charm',
 'chart',
 'chase',
 'chastain',
 'chat',
 'chauffeur',
 'chazz',
 'cheadl',
 'cheat',
 'check',
 'cheerlead',
 'chef',
 'chelsea',
 'chemic',
 'chen',
 'cher',
 'cheryl',
 'chestnut',
 'chevi',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childhood',
 'children',
 'chill',
 'china',
 'chines',
 'chip',
 'chipmunk',
 'chiwetel',
 'chloe',
 'chloÃ«',
 'chocol',
 'choic',
 'choice',
 'choir',
 'choos',
 'chopra',
 'chosen',
 'chow',
 'chri',
 'christ',
 'christensen',
 'christian',
 'christin',
 'christina',
 'christma',
 'christmas',
 'christoph',
 'chronicl',
 'chuck',
 'church',
 'cia',
 'cigar',
 'cigarett',
 'cillian',
 'cinema',
 'cinemat',
 'circl',
 'circu',
 'circuit',
 'circumst',
 'citi',
 'citizen',
 'city',
 'civil',
 'civilian',
 'claim',
 'clair',
 'clan',
 'clark',
 'clash',
 'class',
 'classic',
 'classmat',
 'classroom',
 'clau',
 'claud',
 'claudia',
 'clay',
 'clean',
 'clear',
 'clerk',
 'client',
 'cliff',
 'climat',
 'climb',
 'clint',
 'clive',
 'clock',
 'clone',
 'clooney',
 'close',
 'closer',
 'closet',
 'cloud',
 'clown',
 'club',
 'clue',
 'clumsi',
 'clutch',
 'coach',
 'coal',
 'coast',
 'cocain',
 'code',
 'codi',
 'coen',
 'coffin',
 'cohen',
 'col',
 'cold',
 'cole',
 'coleman',
 'colin',
 'collaps',
 'colleagu',
 'collect',
 'collector',
 'colleg',
 'college',
 'collett',
 'collid',
 'collin',
 'collis',
 'colonel',
 'coloni',
 'color',
 'colorado',
 'columbu',
 'coma',
 'combat',
 'combin',
 'come',
 'comeback',
 'comed',
 'comedi',
 'comedian',
 'comedy',
 'comet',
 'comfort',
 'comic',
 'coming',
 'command',
 'commando',
 'commerci',
 'commit',
 'common',
 'commun',
 'community',
 'compani',
 'companion',
 'company',
 'compet',
 'competit',
 'competition',
 'complet',
 'complex',
 'complic',
 'compos',
 'compuls',
 'comput',
 'conan',
 'concentr',
 'concern',
 'concert',
 'condit',
 'condition',
 'confeder',
 'confer',
 'confess',
 'confid',
 'confin',
 'conflict',
 'confront',
 'confus',
 'congress',
 'connect',
 'connel',
 'connelli',
 'conneri',
 'conni',
 'connor',
 'conquer',
 'conrad',
 'consequ',
 'consequences',
 'conserv',
 'consid',
 'conspir',
 'conspiraci',
 'conspiracy',
 'constant',
 'constantli',
 'construct',
 'consum',
 'contact',
 'contain',
 'contemporari',
 'contend',
 'content',
 'contest',
 'continu',
 'contract',
 'contractor',
 'control',
 'controversi',
 'conveni',
 'convent',
 'converg',
 'convers',
 'convert',
 'convict',
 'convinc',
 'cook',
 'cool',
 'cooper',
 'cop',
 'cope',
 'coppola',
 ...]

In [39]:
'''

Calculationg the distance between two vectors

here we are not interesed in uclidian distance , but in cosine distance
if cosine distance is small the two vectors are closer to each other , else enough long to each other

similarity ~ 1/distances

'''

from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vectors)   #similarity of movie with all others 
similarity                                #similarity itself is 1 else <1

array([[1.        , 0.06692745, 0.06554735, ..., 0.04442617, 0.03244428,
        0.        ],
       [0.06692745, 1.        , 0.04167571, ..., 0.03766218, 0.        ,
        0.01756008],
       [0.06554735, 0.04167571, 1.        , ..., 0.01844278, 0.0808122 ,
        0.        ],
       ...,
       [0.04442617, 0.03766218, 0.01844278, ..., 1.        , 0.03651484,
        0.03108349],
       [0.03244428, 0.        , 0.0808122 , ..., 0.03651484, 1.        ,
        0.06810052],
       [0.        , 0.01756008, 0.        , ..., 0.03108349, 0.06810052,
        1.        ]])

In [40]:
similarity.shape

(4806, 4806)

In [41]:
'''

steps to recomend the movie
1. a movie is given 
2. find index of that movie in our data in similarity
3. sort the similarity 
4. pick top 5 movies 

'''

'\n\nsteps to recomend the movie\n1. a movie is given \n2. find index of that movie in our data in similarity\n3. sort the similarity \n4. pick top 5 movies \n\n'

In [42]:
#fetching the index
movies['title']=='Avatar'
movies[movies['title']=='Avatar']
movies[movies['title']=='Avatar'].index
movies[movies['title']=='Avatar'].index[0]

0

In [43]:
#sorting without loosing the index  
list(enumerate(similarity[0]))

[(0, 0.9999999999999998),
 (1, 0.06692744814102546),
 (2, 0.06554735253444621),
 (3, 0.04335549847620599),
 (4, 0.28791446098121787),
 (5, 0.1433848336691011),
 (6, 0.035121967934313526),
 (7, 0.11654330934961299),
 (8, 0.03771571432023571),
 (9, 0.10036938356837077),
 (10, 0.11029436104106954),
 (11, 0.07733602811121824),
 (12, 0.054410718758250876),
 (13, 0.024738534799764667),
 (14, 0.1577233170360112),
 (15, 0.06855106213838522),
 (16, 0.10366105360784114),
 (17, 0.108147614087175),
 (18, 0.13006649542861798),
 (19, 0.06855106213838522),
 (20, 0.05528134553975607),
 (21, 0.06362847629757777),
 (22, 0.04415107856883479),
 (23, 0.05309942440535914),
 (24, 0.04518564248465834),
 (25, 0.06309151753013043),
 (26, 0.16427061504961218),
 (27, 0.20519567041703077),
 (28, 0.06955186050933215),
 (29, 0.052288698561600205),
 (30, 0.09809657456746182),
 (31, 0.14808721943977307),
 (32, 0.07894736842105261),
 (33, 0.09558988911273406),
 (34, 0.0),
 (35, 0.1675415633166782),
 (36, 0.15897016107942194),
 (37, 0.08549819600709618),
 (38, 0.06494054168326638),
 (39, 0.09453802374948816),
 (40, 0.04682929057908469),
 (41, 0.21341639745917707),
 (42, 0.0),
 (43, 0.08812102431690699),
 (44, 0.03771571432023571),
 (45, 0.06578947368421051),
 (46, 0.17013926184468012),
 (47, 0.29872649174302535),
 (48, 0.09959431881428263),
 (49, 0.03877833671647406),
 (50, 0.07079923254047886),
 (51, 0.09895413919905867),
 (52, 0.22790142204853647),
 (53, 0.11764957176360046),
 (54, 0.01938916835823703),
 (55, 0.04499212706658475),
 (56, 0.24722569302909875),
 (57, 0.06302534916632545),
 (58, 0.045580284409707295),
 (59, 0.054437944538667765),
 (60, 0.011357771260606367),
 (61, 0.25958499574503335),
 (62, 0.04891159880445184),
 (63, 0.08285522649991611),
 (64, 0.064888568452305),
 (65, 0.042601432284230495),
 (66, 0.014451832825401996),
 (67, 0.1946978894863169),
 (68, 0.07733602811121824),
 (69, 0.026871538646250696),
 (70, 0.11712303424679454),
 (71, 0.08193419066805777),
 (72, 0.12725695259515554),
 (73, 0.01911797782254681),
 (74, 0.24678382369818677),
 (75, 0.08456376143646728),
 (76, 0.06424925662032355),
 (77, 0.01981850088223545),
 (78, 0.030934411244487297),
 (79, 0.07894736842105261),
 (80, 0.028878211074619464),
 (81, 0.07950439882424458),
 (82, 0.08031157077540443),
 (83, 0.22213082915965962),
 (84, 0.074215604399294),
 (85, 0.08017658293783156),
 (86, 0.08549819600709618),
 (87, 0.17099639201419237),
 (88, 0.04598545046137244),
 (89, 0.04730472703803727),
 (90, 0.03627381250550058),
 (91, 0.20991342856239587),
 (92, 0.04204138910034078),
 (93, 0.05691103932244722),
 (94, 0.2866297455600074),
 (95, 0.25362863675089403),
 (96, 0.06622661785325219),
 (97, 0.07530940414109723),
 (98, 0.04966996338993915),
 (99, 0.015193428136569098),
 (100, 0.07024393586862705),
 (101, 0.1541517600345829),
 (102, 0.11764957176360048),
 (103, 0.08226127456606226),
 (104, 0.046401616866730944),
 (105, 0.09068453126375145),
 (106, 0.05162257329196673),
 (107, 0.1106817677872384),
 (108, 0.1615552112476628),
 (109, 0.056573571480353566),
 (110, 0.1361331925293325),
 (111, 0.17497830981833887),
 (112, 0.08111071056538126),
 (113, 0.027036903521793755),
 (114, 0.027226638505866502),
 (115, 0.05564148840746572),
 (116, 0.045580284409707295),
 (117, 0.030386856273138196),
 (118, 0.021030505843376807),
 (119, 0.06716604942594676),
 (120, 0.0),
 (121, 0.0734718358370645),
 (122, 0.09304036594559835),
 (123, 0.09464970485606018),
 (124, 0.07530940414109723),
 (125, 0.08433490104000932),
 (126, 0.07530940414109723),
 (127, 0.14429582107316452),
 (128, 0.03498557142706597),
 (129, 0.09334163073596637),
 (130, 0.014013796366780261),
 (131, 0.08849904067559858),
 (132, 0.04204138910034078),
 (133, 0.03121952705272313),
 (134, 0.07647191129018724),
 (135, 0.0),
 (136, 0.015328483487124145),
 (137, 0.020602141085758228),
 (138, 0.11969747440993465),
 (139, 0.07836039099693788),
 (140, 0.041427613249958056),
 (141, 0.16556654463313047),
 (142, 0.05073825686188037),
 (143, 0.07894736842105261),
 (144, 0.07295405746286962),
 (145, 0.07690914705058355),
 (146, 0.05518884821104349),
 (147, 0.11243619908556621),
 (148, 0.05510387687779837),
 (149, 0.2896811091620759),
 (150, 0.22941573387056174),
 (151, 0.12540051368250324),
 (152, 0.04916051440083466),
 (153, 0.0519524333466131),
 (154, 0.03721614637823934),
 (155, 0.025811286645983363),
 (156, 0.14975189244419534),
 (157, 0.06083303292403594),
 (158, 0.32221296812463285),
 (159, 0.056573571480353566),
 (160, 0.07455250649740336),
 (161, 0.059016710652347516),
 (162, 0.059016710652347516),
 (163, 0.06759225880448438),
 (164, 0.05247835714059896),
 (165, 0.056055185467121044),
 (166, 0.10259783520851543),
 (167, 0.059016710652347516),
 (168, 0.19664205760333864),
 (169, 0.1343320988518935),
 (170, 0.08408277820068157),
 (171, 0.04518564248465834),
 (172, 0.11589658124319134),
 (173, 0.031814238148788886),
 (174, 0.09597148699373931),
 (175, 0.04335549847620599),
 (176, 0.014227759830611805),
 (177, 0.021677749238102995),
 (178, 0.016062314155080887),
 (179, 0.04415107856883479),
 (180, 0.013518451760896878),
 (181, 0.02649064714130087),
 (182, 0.08346223261119859),
 (183, 0.05651250986355305),
 (184, 0.30842358510917445),
 (185, 0.10926834468453095),
 (186, 0.043550355630934214),
 (187, 0.10147651372376074),
 (188, 0.047836487323493986),
 (189, 0.07175473098524097),
 (190, 0.06759225880448438),
 (191, 0.04370374100610487),
 (192, 0.08536655898367082),
 (193, 0.06503324771430899),
 (194, 0.015193428136569098),
 (195, 0.051298917604257706),
 (196, 0.07953559537197222),
 (197, 0.05979560915436748),
 (198, 0.03346372407051273),
 (199, 0.06494054168326638),
 (200, 0.16122923187750418),
 (201, 0.01967223688411584),
 (202, 0.018857857160117855),
 (203, 0.08549819600709618),
 (204, 0.028027592733560522),
 (205, 0.03934447376823168),
 (206, 0.1032370802417528),
 (207, 0.12519334891679784),
 (208, 0.12361284651454937),
 (209, 0.03458572319330373),
 (210, 0.07059781184061312),
 (211, 0.04598545046137244),
 (212, 0.04634897746593215),
 (213, 0.05853661322385588),
 (214, 0.0),
 (215, 0.11470786693528086),
 (216, 0.03877833671647406),
 (217, 0.09334163073596637),
 (218, 0.023918243661746993),
 (219, 0.07543142864047142),
 (220, 0.13109470506889243),
 (221, 0.032124628310161774),
 (222, 0.15806712450288418),
 (223, 0.16556654463313047),
 (224, 0.06855106213838522),
 (225, 0.04370374100610487),
 (226, 0.07755667343294811),
 (227, 0.07804881763180782),
 (228, 0.20073876713674155),
 (229, 0.1538057703910978),
 (230, 0.20441907985364974),
 (231, 0.02845551966122361),
 (232, 0.13834289277321493),
 (233, 0.17040572913692198),
 (234, 0.06622661785325218),
 (235, 0.04818694246524266),
 (236, 0.20561572340611634),
 (237, 0.03877833671647406),
 (238, 0.09131087488821056),
 (239, 0.2752988806446741),
 (240, 0.028027592733560522),
 (241, 0.04966996338993915),
 (242, 0.06024752331287778),
 (243, 0.0512989176042577),
 (244, 0.048666426339228755),
 (245, 0.04173111630559929),
 (246, 0.09673016668133488),
 (247, 0.0),
 (248, 0.026669037353133248),
 (249, 0.17040572913692198),
 (250, 0.0),
 (251, 0.07336739820667776),
 (252, 0.011831213107007523),
 (253, 0.09895413919905867),
 (254, 0.044060512158453496),
 (255, 0.0),
 (256, 0.11470786693528087),
 (257, 0.04268327949183541),
 (258, 0.023537557657892522),
 (259, 0.032124628310161774),
 (260, 0.29135827337403253),
 (261, 0.04204138910034078),
 (262, 0.07404360971988654),
 (263, 0.055824219567359015),
 (264, 0.0),
 (265, 0.016912752287293456),
 (266, 0.07596714068284549),
 (267, 0.12695834376925202),
 (268, 0.028903665650803993),
 (269, 0.016062314155080887),
 (270, 0.2013831050778955),
 (271, 0.09637388493048532),
 (272, 0.018857857160117855),
 (273, 0.009304036594559835),
 (274, 0.05887552214709278),
 (275, 0.11969747440993464),
 (276, 0.03498557142706597),
 (277, 0.03568395510523548),
 (278, 0.33113308926626084),
 (279, 0.1251933489167979),
 (280, 0.0),
 (281, 0.03668369910333888),
 (282, 0.03587736549262049),
 (283, 0.012824729401064425),
 (284, 0.012667364798453496),
 (285, 0.012667364798453496),
 (286, 0.06653536832815835),
 (287, 0.014933692277237473),
 (288, 0.016731862035256364),
 (289, 0.03065696697424829),
 (290, 0.03582871819500093),
 (291, 0.06424925662032355),
 (292, 0.06622661785325219),
 (293, 0.016556654463313048),
 (294, 0.09428928580058928),
 (295, 0.06362847629757777),
 (296, 0.03627381250550058),
 (297, 0.05691103932244722),
 (298, 0.0),
 (299, 0.0468292905790847),
 (300, 0.32481131806711666),
 (301, 0.08511306704001455),
 (302, 0.04818694246524266),
 (303, 0.015609763526361564),
 (304, 0.09154684414630487),
 (305, 0.34217085890846966),
 (306, 0.17914359097500465),
 (307, 0.09308574042571362),
 (308, 0.03419927840283847),
 (309, 0.03993615319154359),
 (310, 0.017292861596651866),
 (311, 0.1113498335207611),
 (312, 0.09365858115816939),
 (313, 0.03382550457458691),
 (314, 0.0),
 (315, 0.05374307729250139),
 (316, 0.038474188203193274),
 (317, 0.042601432284230495),
 (318, 0.0),
 (319, 0.08520286456846099),
 (320, 0.08849904067559858),
 (321, 0.0),
 (322, 0.2533558548547658),
 (323, 0.03721614637823934),
 (324, 0.016731862035256364),
 (325, 0.05247835714059896),
 (326, 0.05073825686188037),
 (327, 0.031814238148788886),
 (328, 0.02597621667330655),
 (329, 0.10259783520851541),
 (330, 0.10039117221153819),
 (331, 0.06667259338283311),
 (332, 0.08111071056538126),
 (333, 0.08111071056538126),
 (334, 0.09280323373346189),
 (335, 0.058271654674806495),
 (336, 0.029135827337403247),
 (337, 0.07466846138618737),
 (338, 0.03934447376823168),
 (339, 0.04726901187474408),
 (340, 0.033113308926626096),
 (341, 0.08365931017628181),
 (342, 0.21371260356627755),
 (343, 0.01141385936102632),
 (344, 0.017914359097500464),
 (345, 0.015467205622243648),
 (346, 0.016912752287293456),
 (347, 0.0324442842261525),
 (348, 0.03877833671647406),
 (349, 0.048666426339228755),
 (350, 0.04682929057908469),
 (351, 0.0),
 (352, 0.01860807318911967),
 (353, 0.05098127419345816),
 (354, 0.013157894736842103),
 (355, 0.032961063021678665),
 (356, 0.05374307729250139),
 (357, 0.0),
 (358, 0.05374307729250139),
 (359, 0.01911797782254681),
 (360, 0.08326256191221612),
 (361, 0.046401616866730944),
 (362, 0.12105003117656304),
 (363, 0.11764957176360048),
 (364, 0.014451832825401996),
 (365, 0.13685996549319585),
 (366, 0.06554735253444621),
 (367, 0.0),
 (368, 0.07647191129018724),
 (369, 0.07059781184061312),
 (370, 0.064888568452305),
 (371, 0.10635399695598369),
 (372, 0.06243905410544626),
 (373, 0.3804429551263411),
 (374, 0.025334729596906993),
 (375, 0.07059781184061312),
 (376, 0.04370374100610487),
 (377, 0.0),
 (378, 0.0),
 (379, 0.0549351050361311),
 (380, 0.03065696697424829),
 (381, 0.0512989176042577),
 (382, 0.0),
 (383, 0.026315789473684206),
 (384, 0.029135827337403247),
 (385, 0.03539961627023943),
 (386, 0.012905643322991682),
 (387, 0.013157894736842103),
 (388, 0.0),
 (389, 0.11020775375559674),
 (390, 0.03382550457458691),
 (391, 0.06917144638660747),
 (392, 0.016912752287293456),
 (393, 0.015193428136569098),
 (394, 0.014567913668701624),
 (395, 0.05298129428260174),
 (396, 0.026851080677052733),
 (397, 0.03346372407051273),
 (398, 0.0),
 (399, 0.014808721943977306),
 (400, 0.10039117221153819),
 (401, 0.15058675831730728),
 (402, 0.045580284409707295),
 (403, 0.0604563541758343),
 (404, 0.10259783520851541),
 (405, 0.026669037353133248),
 (406, 0.026144349280800103),
 (407, 0.06131393394849658),
 (408, 0.01911797782254681),
 (409, 0.0),
 (410, 0.06282808624375431),
 (411, 0.046401616866730944),
 (412, 0.10280786170305815),
 (413, 0.10926834468453095),
 (414, 0.018367958959266125),
 (415, 0.05348281873006976),
 (416, 0.04518564248465834),
 (417, 0.03673591791853225),
 (418, 0.0899842541331695),
 (419, 0.11846977555181845),
 (420, 0.1007265930331758),
 (421, 0.012369267399882334),
 (422, 0.10375716957991118),
 (423, 0.05407380704358751),
 (424, 0.024738534799764667),
 (425, 0.048098607024388174),
 (426, 0.06653536832815836),
 (427, 0.018857857160117855),
 (428, 0.05395404209689377),
 (429, 0.0),
 (430, 0.1216660658480719),
 (431, 0.015061880828219446),
 (432, 0.2364763257317293),
 (433, 0.01911797782254681),
 (434, 0.0),
 (435, 0.019968076595771794),
 (436, 0.016386838133611553),
 (437, 0.017292861596651866),
 (438, 0.09453802374948816),
 (439, 0.04818694246524266),
 (440, 0.015061880828219446),
 (441, 0.05309942440535914),
 (442, 0.036893922595746136),
 (443, 0.048636038308579745),
 (444, 0.012824729401064425),
 (445, 0.07466846138618737),
 (446, 0.05647824947249049),
 (447, 0.04235868710436787),
 (448, 0.0805532420311582),
 (449, 0.08957179548750233),
 (450, 0.039735970711951306),
 (451, 0.014933692277237473),
 (452, 0.011707322644771175),
 (453, 0.015193428136569098),
 (454, 0.19619314913492364),
 (455, 0.041130637283031124),
 (456, 0.1290564332299168),
 (457, 0.05510387687779837),
 (458, 0.029867384554474945),
 (459, 0.11314714296070713),
 (460, 0.061868822488974594),
 (461, 0.30442954117128224),
 (462, 0.11024280153951839),
 (463, 0.05990422978731538),
 (464, 0.0),
 (465, 0.022075539284417394),
 (466, 0.17660431427533915),
 (467, 0.07169241683455055),
 (468, 0.017099639201419235),
 (469, 0.07175473098524097),
 (470, 0.04598545046137244),
 (471, 0.06759225880448438),
 (472, 0.08549819600709618),
 (473, 0.13006649542861795),
 (474, 0.0),
 (475, 0.05523681766661074),
 (476, 0.10838874619051497),
 (477, 0.0),
 (478, 0.05468482990747588),
 (479, 0.0604563541758343),
 (480, 0.18074256993863336),
 (481, 0.015328483487124145),
 (482, 0.013518451760896878),
 (483, 0.1399422857082639),
 (484, 0.03771571432023571),
 (485, 0.044426165831931916),
 (486, 0.05213993951603676),
 (487, 0.11980845957463077),
 (488, 0.054437944538667765),
 (489, 0.0),
 (490, 0.13497638119975425),
 (491, 0.08658487179917634),
 (492, 0.06765100914917382),
 (493, 0.02995211489365769),
 (494, 0.020277677641345315),
 (495, 0.12695834376925205),
 (496, 0.023537557657892522),
 (497, 0.0),
 (498, 0.05990422978731538),
 (499, 0.0),
 (500, 0.015193428136569098),
 (501, 0.04634897746593215),
 (502, 0.24165972609347458),
 (503, 0.04682929057908469),
 (504, 0.0),
 (505, 0.13382584475782766),
 (506, 0.08111071056538126),
 (507, 0.3231104224953257),
 (508, 0.07664241743562072),
 (509, 0.014933692277237473),
 (510, 0.08193419066805777),
 (511, 0.07443229275647868),
 (512, 0.06554735253444621),
 (513, 0.08885233166386383),
 (514, 0.025811286645983363),
 (515, 0.0324442842261525),
 (516, 0.014686837386151166),
 (517, 0.05098127419345816),
 (518, 0.044060512158453496),
 (519, 0.0),
 (520, 0.0),
 (521, 0.013809204416652685),
 (522, 0.014933692277237473),
 (523, 0.033113308926626096),
 (524, 0.09637388493048532),
 (525, 0.06077371254627639),
 (526, 0.05564148840746572),
 (527, 0.016912752287293456),
 (528, 0.013809204416652685),
 (529, 0.14599927901768628),
 (530, 0.03721614637823934),
 (531, 0.09397878236968457),
 (532, 0.08918325397005952),
 (533, 0.03934447376823168),
 (534, 0.07694837640638655),
 (535, 0.08740748201220974),
 (536, 0.11654330934961299),
 (537, 0.04415107856883479),
 (538, 0.0),
 (539, 0.27912109783679506),
 (540, 0.045580284409707295),
 (541, 0.24366985862022408),
 (542, 0.03754696307413191),
 (543, 0.047721357223183325),
 (544, 0.032773676267223106),
 (545, 0.044426165831931916),
 (546, 0.04055535528269063),
 (547, 0.05510387687779837),
 (548, 0.014227759830611805),
 (549, 0.23308661869922598),
 (550, 0.015467205622243648),
 (551, 0.023662426214015046),
 (552, 0.0),
 (553, 0.016731862035256364),
 (554, 0.0),
 (555, 0.04008829146891578),
 (556, 0.08193419066805777),
 (557, 0.19918863762856526),
 (558, 0.04966996338993915),
 (559, 0.03877833671647406),
 (560, 0.02305714879553582),
 (561, 0.03627381250550058),
 (562, 0.017292861596651866),
 (563, 0.015756337291581362),
 (564, 0.1630554699247529),
 (565, 0.04335549847620599),
 (566, 0.012905643322991682),
 (567, 0.016062314155080887),
 (568, 0.1183892660110542),
 (569, 0.04598545046137244),
 (570, 0.041204282171516456),
 (571, 0.10705186531570646),
 (572, 0.06622661785325218),
 (573, 0.024318019154289872),
 (574, 0.014227759830611805),
 (575, 0.07169241683455055),
 (576, 0.046401616866730944),
 (577, 0.30588764516074896),
 (578, 0.02488363008967197),
 (579, 0.1749783098183389),
 (580, 0.014338483366910109),
 (581, 0.23288666826750604),
 (582, 0.29314232661238443),
 (583, 0.03568395510523548),
 (584, 0.07336739820667776),
 (585, 0.10729938440986901),
 (586, 0.10012523486435176),
 (587, 0.13809204416652687),
 (588, 0.017292861596651866),
 (589, 0.11615078990692514),
 (590, 0.01911797782254681),
 (591, 0.0645282166149584),
 (592, 0.11615078990692514),
 (593, 0.03668369910333888),
 (594, 0.028239124736245246),
 (595, 0.25387276871303704),
 (596, 0.059234887775909226),
 (597, 0.033113308926626096),
 (598, 0.04415107856883479),
 (599, 0.10814761408717502),
 (600, 0.046401616866730944),
 (601, 0.04055535528269063),
 (602, 0.061868822488974594),
 (603, 0.03065696697424829),
 (604, 0.03877833671647406),
 (605, 0.016386838133611553),
 (606, 0.02282771872205264),
 (607, 0.074215604399294),
 (608, 0.0),
 (609, 0.04204138910034078),
 (610, 0.0691073690718941),
 (611, 0.058271654674806495),
 (612, 0.057353933467640436),
 (613, 0.01938916835823703),
 (614, 0.028676966733820218),
 (615, 0.029135827337403247),
 (616, 0.01938916835823703),
 (617, 0.14912022701586514),
 (618, 0.08371385281611447),
 (619, 0.0),
 (620, 0.0),
 (621, 0.051298917604257706),
 (622, 0.013710212427677042),
 (623, 0.015328483487124145),
 (624, 0.09428928580058928),
 (625, 0.04818694246524266),
 (626, 0.17920430732684967),
 (627, 0.08365931017628181),
 (628, 0.14273582042094193),
 (629, 0.028239124736245246),
 (630, 0.030386856273138196),
 (631, 0.034412360080584264),
 (632, 0.10147651372376074),
 (633, 0.11615078990692515),
 (634, 0.07664241743562072),
 (635, 0.09462916232627815),
 (636, 0.013809204416652685),
 (637, 0.030934411244487297),
 (638, 0.03934447376823168),
 (639, 0.015467205622243648),
 (640, 0.0402766210155791),
 (641, 0.0),
 (642, 0.14227759830611805),
 (643, 0.18560646746692377),
 (644, 0.029867384554474945),
 (645, 0.026669037353133248),
 (646, 0.06424925662032355),
 (647, 0.056055185467121044),
 (648, 0.016062314155080887),
 (649, 0.0),
 (650, 0.044801076831712416),
 (651, 0.0),
 (652, 0.02761840883330537),
 (653, 0.07543142864047142),
 (654, 0.06748819059987712),
 (655, 0.04682929057908469),
 (656, 0.014013796366780261),
 (657, 0.04521000789084244),
 (658, 0.039216523921200154),
 (659, 0.014808721943977306),
 (660, 0.10138838820672658),
 (661, 0.2838874869788344),
 (662, 0.0),
 (663, 0.0),
 (664, 0.03582871819500093),
 (665, 0.04370374100610487),
 (666, 0.10039117221153818),
 (667, 0.0),
 (668, 0.07755667343294811),
 (669, 0.020942695414584774),
 (670, 0.05967860100145693),
 (671, 0.056055185467121044),
 (672, 0.016731862035256364),
 (673, 0.03647702873143481),
 (674, 0.08278327231656524),
 (675, 0.0468292905790847),
 (676, 0.015756337291581362),
 (677, 0.08111071056538127),
 (678, 0.07647191129018724),
 (679, 0.0),
 (680, 0.16289594138375035),
 (681, 0.04966996338993915),
 (682, 0.012667364798453496),
 (683, 0.03012376165643889),
 (684, 0.04055535528269063),
 (685, 0.01967223688411584),
 (686, 0.056573571480353566),
 (687, 0.09832102880166932),
 (688, 0.040555355282690636),
 (689, 0.0),
 (690, 0.02445579940222592),
 (691, 0.044801076831712416),
 (692, 0.23475647508309563),
 (693, 0.015756337291581362),
 (694, 0.02488363008967197),
 (695, 0.04966996338993915),
 (696, 0.026315789473684206),
 (697, 0.0),
 (698, 0.043015450100730324),
 (699, 0.02341464528954235),
 (700, 0.015609763526361564),
 (701, 0.056573571480353566),
 (702, 0.012159009577144936),
 (703, 0.013518451760896878),
 (704, 0.09197090092274487),
 (705, 0.014686837386151166),
 (706, 0.014338483366910109),
 (707, 0.0),
 (708, 0.032124628310161774),
 (709, 0.053702161354105465),
 (710, 0.03627381250550058),
 (711, 0.032773676267223106),
 (712, 0.013809204416652685),
 (713, 0.048098607024388174),
 (714, 0.0),
 (715, 0.08111071056538126),

In [44]:
sorted(list(enumerate(similarity[0])) ,reverse = True) #this sortting done on basis of index but we want on similarity
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])

# but we want first 5 movies

sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

[(2409, 0.4935676473963735),
 (4336, 0.4113063728303113),
 (1537, 0.3880712182748949),
 (3162, 0.3879852850993631),
 (373, 0.3804429551263411)]

In [45]:
def recomend(movi):
    movie_index = movies[movies['title']==movi].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    for i in movies_list:
        print(movies.iloc[i[0]].title)

In [46]:
recomend('Avatar')

Aliens
Silent Running
Moonraker
Alien
Mission to Mars

In [47]:
recomend('Batman Begins')

The Dark Knight
The Dark Knight Rises
Batman
Batman
Batman & Robin

In [48]:
recomend('Spectre')

Quantum of Solace
Skyfall
Never Say Never Again
Die Another Day
Dr. No